# Generated by Django 6.0.7 on 2026-07-12 17:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_contact', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('normalized_location', models.CharField(blank=True, db_index=True, max_length=500)),
                ('submitted_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('detected_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('accident', 'Accident'), ('crime', 'Crime'), ('flood', 'Flood'), ('utility', 'Utility'), ('public_service', 'Public Service'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('features', models.JSONField(blank=True, default=dict)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('fallback', 'Fallback'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('description_embedding', models.JSONField(blank=True, null=True)),
                ('possible_duplicate', models.BooleanField(db_index=True, default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('duplicate_group_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('duplicate_detection_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('fallback', 'Fallback'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('priority_score', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('matched_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_duplicates', to='api.report')),
            ],
            options={
                'ordering': ['-priority_score', 'created_at'],
                'indexes': [models.Index(fields=['category', 'urgency', 'status'], name='api_report_categor_cc8930_idx'), models.Index(fields=['possible_duplicate', 'duplicate_count'], name='api_report_possibl_f32245_idx'), models.Index(fields=['-priority_score', 'created_at'], name='api_report_priorit_bc6cdc_idx')],
            },
        ),
    ]
