# Generated by Django 6.0.7 on 2026-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duplicate_detection_method',
            field=models.CharField(choices=[('embedding', 'Embedding'), ('keyword_fallback', 'Keyword Fallback'), ('unavailable', 'Unavailable')], default='unavailable', max_length=30),
        ),
    ]
