from core.constants.duplicate_detection import (
    CATEGORY_WEIGHT,
    DESCRIPTION_WEIGHT,
    DUPLICATE_THRESHOLD,
    DUPLICATE_WINDOW_HOURS,
    EMBEDDING_DIMENSIONS,
    EMBEDDING_MODEL_NAME,
    LOCATION_WEIGHT,
    MIN_DESCRIPTION_SIMILARITY,
    MIN_LOCATION_SIMILARITY,
    TEMPORAL_WEIGHT,
)

STRONG_DUPLICATE_THRESHOLD = 0.86
MAX_CANDIDATES = 50

FALLBACK_DESCRIPTION_WEIGHT = 0.50
FALLBACK_LOCATION_WEIGHT = 0.35
FALLBACK_CATEGORY_WEIGHT = 0.10
FALLBACK_TEMPORAL_WEIGHT = 0.05

DETECTION_METHOD_EMBEDDING = "embedding"
DETECTION_METHOD_KEYWORD_FALLBACK = "keyword_fallback"
DETECTION_METHOD_UNAVAILABLE = "unavailable"

DETECTION_STATUS_COMPLETED = "completed"
DETECTION_STATUS_FALLBACK = "fallback"
DETECTION_STATUS_FAILED = "failed"
