EMBEDDING_MODEL_NAME = (
    "sentence-transformers/"
    "paraphrase-multilingual-MiniLM-L12-v2"
)

EMBEDDING_DIMENSIONS = 384
DUPLICATE_WINDOW_HOURS = 72

MIN_DESCRIPTION_SIMILARITY = 0.72
MIN_LOCATION_SIMILARITY = 0.60
DUPLICATE_THRESHOLD = 0.78

DESCRIPTION_WEIGHT = 0.55
LOCATION_WEIGHT = 0.30
CATEGORY_WEIGHT = 0.10
TEMPORAL_WEIGHT = 0.05
